---
DISABLE_LINTERS:
  # Has some problems reading referenced policy files. I created a separate workflow for TfLint as it creates valuable output.
  - TERRAFORM_TFLINT
  # Seems very, very slow compared to other linters.
  - TERRAFORM_KICS
  # Nice linter to report CVEs and other cool stuff. But it reports problems with the Terraform code which can't be disabled by
  # configuration.
  - REPOSITORY_TRIVY
  # The tables created by TfDoc are not formatted according to the standard. And there is no option to deactivate the check for a
  # section of the file.
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  # CSpell does a great job. No need for a second linter.
  - SPELL_MISSPELL
