formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: true

sections:
  hide: []
  show: []

content: ""

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
